import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from Aryan Kumar" }]);

  return (
    <>
      <Head>
        <title>hero ranking</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen w-screen flex flex-col justify-center">
        <div className="text-2xl text-center"> Which Hero do you Like More? </div>
        
        <div className="p-3" />
        
        <div className="border rounded p-8 flex justify-between"> 
          <div className="w-16 h-16 bg-red-200" />
          <div className="p-8"> vs </div>
          <div className= "w-16 h-16 bg-red-200"/>
        </div>
      </div>
      
    </>
  );
};

export default Home;
